MAYA-127045 Only run reparenting tests of Shaders, NodeGraphs and Materials for Maya2023 and later.
In Maya 2022, reparenting something to a Material results in:
```
RuntimeError: Object [path/to/material] does not support parenting and therefore cannot be a parent.
```