Fix a regression that was recently introduced in commitID: 85010f26 when running TestPxrUsdTranslators.
See below error message:

API error detected in /home/sabrih/Desktop/maya-usd/plugin/pxr/maya/plugin/pxrUsd/plugin.cpp at line 106
(kFailure): Unexpected Internal Failure
Error: line 1: initializePlugin function failed (pxrUsd)
AttributeError: 'module' object has no attribute 'usdExport'