/permissive flag will trigger a compiler error in older version of boost::python
error C3861: 'unwind_type': identifier not found

Conditionally add this flag based on the Pixar version since boost::python coming with the later version of USD don't have this issue.