Fix MaterialX compilation on M1 Macs
Fixes #2267 ?

Removes a global struct that was used to pass vertex data around.

This is an educated guess based on the GLSL compilation error message I received:
```
ERROR: 0:338: Missing initializer for const variable ‘g_mxVertexData’
ERROR: 0:1557: Use of undeclared identifier ‘g_mxVertexData’
ERROR: 0:1558: Use of undeclared identifier ‘g_mxVertexData’
ERROR: 0:1559: Use of undeclared identifier ‘g_mxVertexData’
```